### ISSUE TITLE
Ansible server issues

### ISSUE THREAD

**Issue by Dhariaj** [aws-quickstart/quickstart-redhat-openshift#117] opened 2018-04-13 14:43 UTC
I am using the new template that was released on April, 6, 2018 and having issues with the ansible server. The error log is pasted below and I checked the host file and it looks empty. Up until yesterday the host file was getting populated but the Ansible was not able to SSH to just the master nodes and now today this...

ansible-playbook /usr/share/ansible/openshift-ansible/playbooks/prerequisites.yml
Apr 13 14:18:37 ip-10-1x.x.x cloud-init: [WARNING]: provided hosts list is empty, only localhost is available. Note
Apr 13 14:18:37 ip-10-x.x.x cloud-init: that the implicit localhost does not match 'all'
Apr 13 14:18:38 ip-10-1x.x.x cloud-init: + qs_err ' Openshift installation failed, see logs for details '

**Comment by Dhariaj** [comment] 2018-04-13 14:46
I am using the new template that was released on   April, 6, 2018 and having issues with the ansible server.  The error log is pasted below and I checked the host file and it looks empty.  Up until yesterday the host file was getting populated but the Ansible was not able to SSH to just the master nodes and now today this... 

+ ansible-playbook /usr/share/ansible/openshift-ansible/playbooks/prerequisites.yml
Apr 13 14:18:37 ip-10-160-9-95 cloud-init: [WARNING]: provided hosts list is empty, only localhost is available. Note
Apr 13 14:18:37 ip-10-160-9-95 cloud-init: that the implicit localhost does not match 'all'
Apr 13 14:18:38 ip-10-160-9-95 cloud-init: + qs_err ' Openshift installation failed, see logs for details '

**Comment by jaymccon** [comment] 2018-04-13 21:06
@Dhariaj sounds like the command to populate the hosts file is failing for some reason, are you able to run it by hand on the ansible instance and checking for errors:

`/bin/aws-ose-qs-scale --generate-initial-inventory --write-hosts-to-tempfiles`

I've also picked up that we were handling errors on that command which would have resulted in the bootstrapping continuing, even if there were errors in the process, I'm busy testing a fix for that, which should make troubleshooting issues like this easier.

**Comment by Dhariaj** [comment] 2018-04-16 13:13
I will test this out today... Out of curiosity is there a way to suppressed the certificate request and use a self signed one?

**Comment by Dhariaj** [comment] 2018-04-16 13:16
Got the following error 

[root@ip-10-x-x- ec2-user]# /bin/aws-ose-qs-scale --generate-initial-inventory --write-hosts-to-tempfiles
Traceback (most recent call last):
  File "/bin/aws-ose-qs-scale", line 14, in <module>
    sys.exit(main())
  File "/bin/aws-ose-qs-scale", line 11, in main
    return aws_openshift_quickstart.scaler.main()
  File "/usr/lib/python2.7/site-packages/aws_openshift_quickstart/scaler.py", line 297, in main
    ClusterGroups.setup()
  File "/usr/lib/python2.7/site-packages/aws_openshift_quickstart/utils.py", line 646, in setup
    for group in cls._determine_cluster_groups():
  File "/usr/lib/python2.7/site-packages/aws_openshift_quickstart/utils.py", line 658, in _determine_cluster_groups
    _g = LocalASG(all_groups[i])
  File "/usr/lib/python2.7/site-packages/aws_openshift_quickstart/utils.py", line 470, in __init__
    self.openshift_config_category = self._determine_openshift_category(self.logical_id)
AttributeError: 'LocalASG' object has no attribute 'logical_id'

**Comment by agamzn** [comment] 2018-04-16 19:12
@Dhariaj, 

On each of the 3 ASGs, can you confirm that the following tags are in place - and populated? That value should've been set by these two lines. 

https://github.com/aws-quickstart/quickstart-redhat-openshift/blob/cfefa7df944314ebab1626b7d00063167a13f463/scripts/scaling/aws_openshift_quickstart/utils.py#L467-L468

**Comment by agamzn** [comment] 2018-04-16 19:25
Scratch that. I see what's causing this. Commit forthcoming.

**Comment by Dhariaj** [comment] 2018-04-16 22:29
Awesome! That is good news hopefully my 18th attempt will be successful :)

Sent from my iPhone

On Apr 16, 2018, at 3:24 PM, Andrew G. <notifications@github.com<mailto:notifications@github.com>> wrote:


Scratch that. I see what's causing this. Commit forthcoming.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_aws-2Dquickstart_quickstart-2Dredhat-2Dopenshift_issues_117-23issuecomment-2D381720176&d=DwMCaQ&c=uUZbzTZZgO9xXVRZz77NpQ&r=7JWmtnrZy4WGjKQ01tyHzY4bGM7dWpE-dowS5b7_B20&m=hHYNc2FAYtV0Yo0J0MPrrzjoHb5AaGSoLd5JWH-9lWs&s=HL853fj02p8l5WsFQVvSozcShyir5sp5OKQLeMjbpgA&e=>, or mute the thread<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AklEXOKsMDtv-5FrkF0kb8og3yHRgU2ek4ks5tpPAigaJpZM4TTkjp&d=DwMCaQ&c=uUZbzTZZgO9xXVRZz77NpQ&r=7JWmtnrZy4WGjKQ01tyHzY4bGM7dWpE-dowS5b7_B20&m=hHYNc2FAYtV0Yo0J0MPrrzjoHb5AaGSoLd5JWH-9lWs&s=U_wjCYO8Nt-SxDx62fHaOhTNoR7ug-NkrDOA2-Ko2-A&e=>.



Email transmitted across the Internet is normally not protected and may be intercepted and viewed by others. Therefore, you should refrain from sending any confidential or private information via unsecured email to PenFed. We will not ask you to send confidential information to us via email, such as your logon ID, password, account numbers, or Social Security number. We prohibit our employees from sending confidential information to you via email that is not encrypted. The recommended document submission method is FAX; a partial list of generic fax numbers can be found <https://www.penfed.org/aboutUs/contactUs.asp#fax> here<https://www.penfed.org/aboutUs/contactUs.asp#fax>.<https://www.penfed.org/aboutUs/contactUs.asp#fax>

**Comment by Dhariaj** [comment] 2018-04-17 11:57
Master node Tag
![screen shot 2018-04-17 at 7 56 57 am](https://user-images.githubusercontent.com/38356060/38868411-ee9a0d06-4214-11e8-930d-0275219bd489.png)

**Comment by Dhariaj** [comment] 2018-04-17 11:58
Openshift-node
![screen shot 2018-04-17 at 7 58 02 am](https://user-images.githubusercontent.com/38356060/38868467-12f5a282-4215-11e8-88f9-8e731e776e32.png)

ETCD node
![screen shot 2018-04-17 at 7 58 43 am](https://user-images.githubusercontent.com/38356060/38868485-2488ce16-4215-11e8-86fe-94fb8900ab3e.png)

**Comment by agamzn** [comment] 2018-04-18 13:45
Follow up: I have a fix for this in the develop branch. I ran it through manual testing yesterday and nothing cropped up. We need to have it run through CI, and hope to have this into master later today.

See commit https://github.com/aws-quickstart/quickstart-redhat-openshift/commit/7ab63ab1ad295094170d770cafc15a20189ff83a

**Comment by Dhariaj** [comment] 2018-04-18 13:53
so can I use the same cloud formation template to deploy this in the same VPC?

**Comment by agamzn** [comment] 2018-04-18 14:03
Once the changes are in the master branch, you'll be able to use the same template and re-deploy in an existing VPC. The ASGs, instances, and soforth will be replaced / created along the way.

**Comment by Dhariaj** [comment] 2018-04-18 14:27
dumb question but if I run the template manually in this version by copying and pasting it designer and deploying it using CF Console will it download/get the right dependencies?

**Comment by agamzn** [comment] 2018-04-18 14:32
I don’t immediately see any issues with that. The master template points to our quickstart S3 bucket that hosts all of the assets, and the template points to that bucket. As a word of caution, through the nature of copying and pasting into the designer, you may run into formatting issues. Now, I haven’t seen that happen, but I need to call out that potential.

**Comment by Dhariaj** [comment] 2018-04-18 14:34
Cool I will deploy the template from  commit-7ab63ab and hopefully it works..

**Comment by agamzn** [comment] 2018-04-18 14:51
Our CI tests passed and this commit is now in master.

**Comment by Dhariaj** [comment] 2018-04-18 15:11
I deployed the template again and got the same error message again.. Will try the master REPO now


[root@ip-10-x.x.x ec2-user]# /bin/aws-ose-qs-scale --generate-initial-inventory --write-hosts-to-tempfiles
Traceback (most recent call last):
  File "/bin/aws-ose-qs-scale", line 14, in <module>
    sys.exit(main())
  File "/bin/aws-ose-qs-scale", line 11, in main
    return aws_openshift_quickstart.scaler.main()
  File "/usr/lib/python2.7/site-packages/aws_openshift_quickstart/scaler.py", line 297, in main
    ClusterGroups.setup()
  File "/usr/lib/python2.7/site-packages/aws_openshift_quickstart/utils.py", line 646, in setup
    for group in cls._determine_cluster_groups():
  File "/usr/lib/python2.7/site-packages/aws_openshift_quickstart/utils.py", line 658, in _determine_cluster_groups
    _g = LocalASG(all_groups[i])
  File "/usr/lib/python2.7/site-packages/aws_openshift_quickstart/utils.py", line 470, in __init__
    self.openshift_config_category = self._determine_openshift_category(self.logical_id)
AttributeError: 'LocalASG' object has no attribute 'logical_id'

**Comment by agamzn** [comment] 2018-04-18 15:25
Line 470 in that case has been moved around and I'm wondering if you're hitting an eventual-consistency with the S3 bucket. If you still have a stack up, please run the following command...

`sed '465,475!d' /root/ose_scaling/aws_openshift_quickstart/utils.py`

If you're using the latest code, you'll see this...

```
        for tag in self._grab_tags(json_doc['Tags']):
            self.__dict__[tag['key']] = tag['value']
        self.in_openshift_cluster = self._determine_cluster_membership()
        if self.in_openshift_cluster:
            self.openshift_config_category = self._determine_openshift_category(self.logical_id)
            # Set the logcal_name
            self.logical_name = InventoryConfig.logical_names[self.logical_id]
            # Sanity check to verify they're in the API.
            # - and populate the InventoryConfig.all_instances dict as a result.
            # - working around edge cases.
            ilist = [i['InstanceId'] for i in json_doc['Instances']]
```

**Comment by Dhariaj** [comment] 2018-04-18 15:29
This is what I see at this moment and it doesn’t look similar to what you wrote…

[root@ip-10-160-9-12 ec2-user]# sed '465,475!d' /root/ose_scaling/aws_openshift_quickstart/utils.py

        if self._cooldown_upperlimit >= 300:
            self._cooldown_upperlimit = 300
        for tag in self._grab_tags(json_doc['Tags']):
            self.__dict__[tag['key']] = tag['value']
        self.in_openshift_cluster = self._determine_cluster_membership()
        self.openshift_config_category = self._determine_openshift_category(self.logical_id)
        if self.in_openshift_cluster:
            # Set the logcal_name
            self.logical_name = InventoryConfig.logical_names[self.logical_id]
            # Sanity check to verify they're in the API.
            # - and populate the InventoryConfig.all_instances dict as a result.


Dharia, Jimmy

**Comment by agamzn** [comment] 2018-04-18 15:33
Thanks. I know we push the master branch to S3 on a regular basis. I need to discuss internally to determine what that schedule is. I'll have an update on this in a bit (today).

**Comment by Dhariaj** [comment] 2018-04-18 16:03
Will you please let me know and then I can test and redeploy?

Dharia, Jimmy

**Comment by agamzn** [comment] 2018-04-18 16:06
Absolutely.

**Comment by agamzn** [comment] 2018-04-18 16:46
S3 is now in sync with the master branch.

**Comment by Dhariaj** [comment] 2018-04-18 16:47
Awesome! Will try to deploy now..

Dharia, Jimmy

**Comment by agamzn** [comment] 2018-04-19 13:26
Hrm. Do you mind uploading the ansible log to an S3 bucket and emailing (vs posting here) the link?

**Comment by Dhariaj** [comment] 2018-04-19 13:52
sure just to give you more info 

[root@ip-10-160-8-249 log]# ansible -m ping all
ip-10-160-12-207.ec2.internal | UNREACHABLE! => {
    "changed": false, 
    "msg": "SSH Error: data could not be sent to remote host \"ip-10-160-12-207.ec2.internal\". Make sure this host can be reached over ssh", 
    "unreachable": true
}
ip-10-160-13-147.ec2.internal | UNREACHABLE! => {
    "changed": false, 
    "msg": "SSH Error: data could not be sent to remote host \"ip-10-160-13-147.ec2.internal\". Make sure this host can be reached over ssh", 
    "unreachable": true
}
ip-10-160-13-225.ec2.internal | UNREACHABLE! => {
    "changed": false, 
    "msg": "SSH Error: data could not be sent to remote host \"ip-10-160-13-225.ec2.internal\". Make sure this host can be reached over ssh", 
    "unreachable": true
}
ip-10-160-14-220.ec2.internal | UNREACHABLE! => {
    "changed": false, 
    "msg": "SSH Error: data could not be sent to remote host \"ip-10-160-14-220.ec2.internal\". Make sure this host can be reached over ssh", 
    "unreachable": true
}
ip-10-160-13-130.ec2.internal | UNREACHABLE! => {
    "changed": false, 
    "msg": "SSH Error: data could not be sent to remote host \"ip-10-160-13-130.ec2.internal\". Make sure this host can be reached over ssh", 
    "unreachable": true
}
ip-10-160-12-94.ec2.internal | UNREACHABLE! => {
    "changed": false, 
    "msg": "SSH Error: data could not be sent to remote host \"ip-10-160-12-94.ec2.internal\". Make sure this host can be reached over ssh", 
    "unreachable": true
}
ip-10-160-12-96.ec2.internal | SUCCESS => {
    "changed": false, 
    "ping": "pong"
}
ip-10-160-14-221.ec2.internal | SUCCESS => {
    "changed": false, 
    "ping": "pong"
}
ip-10-160-14-132.ec2.internal | SUCCESS => {
    "changed": false, 
    "ping": "pong"
}

**Comment by agamzn** [comment] 2018-04-19 13:55
This is very helpful. I'm grabbing (more) coffee and digging further.

**Comment by Dhariaj** [comment] 2018-04-19 13:55
this same thing happened when I first tried to deploy the template and I have confirmed that if I login to the Ansible instance then I can ssh to the same instances that Ansible claims it cannot. Also if I modify the ansible config file and specify ansible user= ec2-user and a path to a local key file then Ansible is able to ssh to all the resources.

**Comment by Dhariaj** [comment] 2018-04-19 14:46
https://s3-us-west-2.amazonaws.com/penfed-smx/ansible.txt here you go

**Comment by agamzn** [comment] 2018-04-19 14:55
Spotted the culprit. I need to do some white-boarding and iron out the best path forward. I'll circle back on this in a few hours with an update.

**Comment by Dhariaj** [comment] 2018-04-19 14:59
I wonder why this works for others?

**Comment by agamzn** [comment] 2018-04-19 17:35
I've added a wrapper that waits for everything to be SSH'able before ansible kicks off. Please give this iteration a run and let us know if you run into anything.

**Comment by Dhariaj** [comment] 2018-04-19 18:27
is this part of the master repo? also I manually generated the log file and got the following error 
Gathering information from hosts...
 [WARNING]: Could not match supplied host pattern, ignoring: oo_lb_to_config
There was a problem fetching the required information. Please see /tmp/ansible.log for details.

also if you look at the host file that is generated it is trying to use root user to login shouldnt that be ec2-user?

**Comment by agamzn** [comment] 2018-04-19 19:05
It's part of the master repo as of my last comment. The warnings that are similar to what you've pasted (Could not match supplied host pattern...) can be ignored. The ansible node intentionally reaches out to the remainder of the cluster as root. We've specifically configured it to do so.

**Comment by Dhariaj** [comment] 2018-04-19 19:09
Ok will redeploy in sometime

Sent from my iPhone

On Apr 19, 2018, at 3:05 PM, Andrew G. <notifications@github.com<mailto:notifications@github.com>> wrote:


It's part of the master repo as of my last comment. The warnings that are similar to what you've pasted (Could not match supplied host pattern...) can be ignored. The ansible node intentionally reaches out to the remainder of the cluster as root. We've specifically configured it to do so.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_aws-2Dquickstart_quickstart-2Dredhat-2Dopenshift_issues_117-23issuecomment-2D382847327&d=DwMFaQ&c=uUZbzTZZgO9xXVRZz77NpQ&r=7JWmtnrZy4WGjKQ01tyHzY4bGM7dWpE-dowS5b7_B20&m=nFEJMx7LoaVAnWj8H92e1BuNyArxA8XzqX2lLUMSDRs&s=3WvFrYF-CFSornhst3SnNQxPBmdYDa4ZfYQ0e-loFQk&e=>, or mute the thread<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AklEXIGFLYG6P2MdcSRi0jXFE3PwnNg2ks5tqOBFgaJpZM4TTkjp&d=DwMFaQ&c=uUZbzTZZgO9xXVRZz77NpQ&r=7JWmtnrZy4WGjKQ01tyHzY4bGM7dWpE-dowS5b7_B20&m=nFEJMx7LoaVAnWj8H92e1BuNyArxA8XzqX2lLUMSDRs&s=aJmf-4ip9gPrRC7rVP3ov8fAKEuwRqtdf1KcfZwwnLA&e=>.



Email transmitted across the Internet is normally not protected and may be intercepted and viewed by others. Therefore, you should refrain from sending any confidential or private information via unsecured email to PenFed. We will not ask you to send confidential information to us via email, such as your logon ID, password, account numbers, or Social Security number. We prohibit our employees from sending confidential information to you via email that is not encrypted. The recommended document submission method is FAX; a partial list of generic fax numbers can be found <https://www.penfed.org/aboutUs/contactUs.asp#fax> here<https://www.penfed.org/aboutUs/contactUs.asp#fax>.<https://www.penfed.org/aboutUs/contactUs.asp#fax>

**Comment by agamzn** [comment] 2018-04-20 14:37
The short answer, a lot. That's the entrypoint to the ansible playbook that provisions the OpenShift cluster. The playbooks are within the openshift-ansible repo. [Here's their folder.](https://github.com/openshift/openshift-ansible/tree/release-3.7/playbooks/byo)

WIthout knowing what you're trying to modify, I recommend you start at config.yml and work your way down the structure.

**Comment by Dhariaj** [comment] 2018-04-20 14:40
Further troubleshooting leads me to believe that this might have something to do with the DHCP options set that we using.  As test and deleted all the DNS servers from resolv.conf and just left the amazonprovideddns with search ec2.internal in the resolv.conf file and it appears to go a lot further but  somewhere down the road it updates the DNS servers back

Apr 20 14:36:42 ip-10-160-13-226 dnsmasq[55716]: setting upstream servers from DBus
Apr 20 14:36:42 ip-10-160-13-226 dnsmasq[55716]: using nameserver 10.160.0.2#53
Apr 20 14:36:42 ip-10-160-13-226 dnsmasq[55716]: using nameserver 10.160.33.122#53
Apr 20 14:36:42 ip-10-160-13-226 dnsmasq[55716]: using nameserver 10.160.32.106#53
Apr 20 14:36:42 ip-10-160-13-226 dnsmasq[55716]: using nameserver 127.0.0.1#53 for domain in-addr.arpa
Apr 20 14:36:42 ip-10-160-13-226 dnsmasq[55716]: using nameserver 127.0.0.1#53 for domain cluster.local
Apr 20 14:36:41 ip-10-160-13-226 atomic-openshift-node: E0420 14:36:41.533391   57089 kubelet_node_status.go:106] Unable to register node "ip-10-160-13-226.ec2.internal" with API server: nodes "ip-10-160-13-226.ec2.internal" is forbidden: node ip-10-160-13-226 cannot modify node ip-10-160-13-226.ec2.internal

**Comment by Dhariaj** [comment] 2018-04-20 14:47
INSTALLER STATUS ***********************************************************************************************************************************************************************
Initialization             : Complete
Health Check               : Complete
etcd Install               : Complete
Master Install             : Complete
Master Additional Install  : Complete
Node Install               : In Progress
	This phase can be restarted by running: playbooks/byo/openshift-node/config.yml



Failure summary:


  1. Hosts:    ip-10-160-12-202.ec2.internal, ip-10-160-12-95.ec2.internal, ip-10-160-13-226.ec2.internal, ip-10-160-13-64.ec2.internal, ip-10-160-14-149.ec2.internal, ip-10-160-14-44.ec2.internal
     Play:     Configure nodes
     Task:     restart node
     Message:  Unable to restart service atomic-openshift-node: Job for atomic-openshift-node.service failed because the control process exited with error code. See "systemctl status atomic-openshift-node.service" and "journalctl -xe" for details.

**Comment by Dhariaj** [comment] 2018-04-20 14:48
Apr 20 14:47:50 ip-10-160-13-226 atomic-openshift-master-api[53100]: I0420 14:47:50.623137   53100 rest.go:362] Starting watch for /api/v1/pods, rv=9407 labels= fields= timeout=7m15s
Apr 20 14:47:51 ip-10-160-13-226 atomic-openshift-node[60245]: W0420 14:47:51.422531   60245 sdn_controller.go:48] Could not find an allocated subnet for node: ip-10-160-13-226, Waiting...
Apr 20 14:47:51 ip-10-160-13-226 sshd[60334]: Did not receive identification string from 10.160.13.123 port 33785
Apr 20 14:47:52 ip-10-160-13-226 sshd[60335]: Did not receive identification string from 10.160.13.123 port 24710
Apr 20 14:47:52 ip-10-160-13-226 sshd[60336]: Did not receive identification string from 10.160.13.123 port 12901
Apr 20 14:47:52 ip-10-160-13-226 sshd[60337]: Did not receive identification string from 10.160.13.123 port 26346
Apr 20 14:47:53 ip-10-160-13-226 sshd[60338]: Did not receive identification string from 10.160.13.123 port 15454
Apr 20 14:47:53 ip-10-160-13-226 atomic-openshift-node[60245]: W0420 14:47:53.519856   60245 cni.go:189] Unable to update cni config: No networks found in /etc/cni/net.d
Apr 20 14:47:53 ip-10-160-13-226 atomic-openshift-node[60245]: E0420 14:47:53.519996   60245 kubelet.go:2112] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not read
Apr 20 14:47:53 ip-10-160-13-226 atomic-openshift-node[60245]: E0420 14:47:53.531323   60245 eviction_manager.go:238] eviction manager: unexpected err: failed GetNode: node 'ip-10-160-13-226.ec2.internal' not found
Apr 20 14:47:53 ip-10-160-13-226 sshd[60339]: Did not receive identification string from 10.160.13.123 port 24880
Apr 20 14:47:54 ip-10-160-13-226 sshd[60340]: Did not receive identification string from 10.160.13.123 port 62123
Apr 20 14:47:54 ip-10-160-13-226 sshd[60342]: Did not receive identification string from 10.160.13.123 port 13940
Apr 20 14:47:54 ip-10-160-13-226 sshd[60343]: Did not receive identification string from 10.160.13.123 port 13530
Apr 20 14:47:55 ip-10-160-13-226 sshd[60344]: Did not receive identification string from 10.160.13.123 port 12002
Apr 20 14:47:55 ip-10-160-13-226 sshd[60345]: Did not receive identification string from 10.160.13.123 port 15565

**Comment by jaymccon** [comment] 2018-04-25 17:36
@Dhariaj can you provide the parameters you are launching the stack with so that I can attempt to reproduce ?

Please be sure to redact your Redhat credentials, OpenShiftAdminPassword and HostedZoneId.

**Comment by jaymccon** [comment] 2018-05-04 04:31
I'm going to close this issue as it has gone quiet and the title is very broad, resulting in many unrelated reports. My advise to anyone finding this message is to first investigate the cause of the ansible server failure by going through the logs (`journalctl | grep cloud-init` and `/var/log/ansible.log`)  and then creating a new issue specific to the error found in these logs

**Closed by jaymccon** 2018-05-04 04:31 UTC
