### ISSUE TITLE
CloudFormation template keeps failing at Ansible Configserver

### ISSUE THREAD

**Issue by wrlong** [aws-quickstart/quickstart-redhat-openshift#11] opened 2017-09-15 13:08 UTC
Great quick start guide so far.  

Attempting to launch CF template but keep failing at the same place, on the Ansible config server.  To that point, the VPC, instances, etc. stacks complete fine.  

From that Ansible config instance, I see the following:

Sep 15 04:03:04 localhost cloud-init: /tmp/quickstart-cfn-tools.source: line 325: /root/redhat_ose-register.sh: No such file or directory

Sep 15 04:03:04 localhost cloud-init: Retrying ....

Sep 15 04:03:04 localhost cloud-init: /tmp/quickstart-cfn-tools.source: line 325: /root/redhat_ose-register.sh: No such file or directory

I have an active subscription and have put in the user/pass/pool-id.  Curious what steps I can take to finish the installation from this point.   That instance also does not seem to have Ansible installed so I dont think its getting far beyond starting the ec2 instances.

Thanks!

**Comment by dougtoppin** [comment] 2017-09-15 13:29
I am on my second attempt to run this. The previous failed on the AnsibleConfigServer related error:
Received FAILURE signal with UniqueId i-0222c0c7c100f51e9

Not sure exact cause yet and am trying again now.

**Comment by wrlong** [comment] 2017-09-15 13:34
Thanks for commenting.  I am getting the same thing in the AWS CF portal: 

Received FAILURE signal with UniqueId i-0b0ee8494fbfde5c5

I have tried this several times with the same result.

**Comment by dougtoppin** [comment] 2017-09-15 14:11
2nd attempt also failed with the cause ".. was not successfully created: The following resource(s) failed to create: [AnsibleConfigServer].".
Not sure exact cause yet. I'm a little hesitant to have the rollback not terminate and remove all AWS resources because there may be a lot of cleanup to do it manually once the cause has been identified.
Reviewing cloudwatch log to see if any more detail there.

**Comment by dougtoppin** [comment] 2017-09-15 14:59
Trying again with delete turned off on rollback. I see this being logged on the ansible server in /var/log/messages

Sep 15 14:54:22 localhost yum[8208]: Installed: epel-release-7-10.noarch
Sep 15 14:54:22 localhost cloud-init: ------------------[] Completed epel configuration
Sep 15 14:54:22 localhost cloud-init: ------------------[] Starting: installation of  awscli
Sep 15 14:54:27 localhost cloud-init: ------------------[] Completed: install of awscli
Sep 15 14:54:27 localhost cloud-init: ========================================================================================================================
Sep 15 14:54:27 localhost cloud-init: ------------------[] Completed: QuickStart Common Utils
Sep 15 14:54:27 localhost cloud-init: ========================================================================================================================
Sep 15 14:54:27 localhost cloud-init: ------------------[]Attach to Subscription pool
Sep 15 14:54:28 localhost cloud-init: fatal error: An error occurred (403) when calling the HeadObject operation: Forbidden
Sep 15 14:54:28 localhost cloud-init: chmod: cannot access ‘/root/redhat_ose-register.sh’: No such file or directory
Sep 15 14:54:28 localhost cloud-init: /tmp/quickstart-cfn-tools.source: line 325: /root/redhat_ose-register.sh: No such file or directory
Sep 15 14:54:28 localhost cloud-init: Retrying ....
Sep 15 14:54:28 localhost cloud-init: /tmp/quickstart-cfn-tools.source: line 325: /root/redhat_ose-register.sh: No such file or directory
Sep 15 14:54:28 localhost cloud-init: Retrying ....
Sep 15 14:54:30 localhost cloud-init: /tmp/quickstart-cfn-tools.source: line 325: /root/redhat_ose-register.sh: No such file or directory
Sep 15 14:54:30 localhost cloud-init: Retrying ....
Sep 15 14:54:34 localhost cloud-init: /tmp/quickstart-cfn-tools.source: line 325: /root/redhat_ose-register.sh: No such file or directory
Sep 15 14:54:34 localhost cloud-init: Retrying ....

**Comment by dougtoppin** [comment] 2017-09-15 15:02
I installed mlocate on the ansible server and looked for redhat_ose-register.sh (not found in the error above). Was not found on the host.

**Comment by dougtoppin** [comment] 2017-09-15 15:08
I checked one of the masters and see the same error so this may or may not be related to the issue.
The following is from a master:

Sep 15 14:56:39 localhost cloud-init: /tmp/quickstart-cfn-tools.source: line 325: /root/redhat_ose-register.sh: No such file or directory
Sep 15 14:56:39 localhost cloud-init: Retrying ....
Sep 15 14:57:17 localhost cloud-init: /tmp/quickstart-cfn-tools.source: line 325: /root/redhat_ose-register.sh: No such file or directory
Sep 15 14:57:17 localhost cloud-init: Tried 20 times and failed!

**Comment by wrlong** [comment] 2017-09-15 15:14
Yes, have seen the same on repeated attempts.  It appears to reference distro-specific init configs in "quickstart-cfn-tools.source" in the submodule repo, which assuming is dependent on "redhat_ose-register.sh" being on the deployed instance.  

"redhat_ose-register.sh" does not appear to be present in /root on any of my instances as you are seeing as well.

**Comment by dougtoppin** [comment] 2017-09-15 15:25
Here are the other errors that I see in various ansible server logs, just for completeness.
Not sure if relevant to the issue(s):

cloud-init.log
2017-09-15 14:52:02,404 - util.py[DEBUG]: Running command ['mount', '-o', 'ro,sync', '-t', 'iso9660', '/dev/xvda', '/tmp/tmpnMIlOQ'] with allowed return codes [0] (shell=False, capture=True)
2017-09-15 14:52:02,417 - util.py[DEBUG]: Failed mount of '/dev/xvda' as 'iso9660': Unexpected error while running command.
Command: ['mount', '-o', 'ro,sync', '-t', 'iso9660', '/dev/xvda', '/tmp/tmpnMIlOQ']
Exit code: 32
Reason: -
Stdout: -
Stderr: mount: /dev/xvda is already mounted or /tmp/tmpnMIlOQ busy
2017-09-15 14:52:02,417 - util.py[DEBUG]: Recursively deleting /tmp/tmpnMIlOQ
2017-09-15 14:52:02,418 - DataSourceOVF.py[DEBUG]: /dev/xvda not mountable as iso9660
2017-09-15 14:52:02,418 - util.py[DEBUG]: Peeking at /dev/xvda1 (max_bytes=512)
2017-09-15 14:52:02,418 - util.py[DEBUG]: Reading from /proc/mounts (quiet=False)
2017-09-15 14:52:02,419 - util.py[DEBUG]: Read 2062 bytes from /proc/mounts

choose_repo.log:
[ERROR:choose_repo] choose_repo:33 2017-07-11 16:01:55,494: Error getting availability zone from EC2 instance metadata.  Are you running in EC2?
[ERROR:choose_repo] choose_repo:35 2017-07-11 16:01:55,495: <urlopen error [Errno 113] No route to host>
[INFO:choose_repo] choose_repo:39 2017-09-15 14:52:05,536: Zone [us-east-1b]

grubby_prune_debug
[1499788759] Start       : Begin search for extraneous debug arguments
[1499788759] Error       : Could not find a bootloader configuration to back up
[1499788759] Exit        : Exiting script

messages:
Sep 15 14:54:27 localhost cloud-init: ------------------[]Attach to Subscription pool
Sep 15 14:54:28 localhost cloud-init: fatal error: An error occurred (403) when calling the HeadObject operation: Forbidden
Sep 15 14:54:28 localhost cloud-init: chmod: cannot access ‘/root/redhat_ose-register.sh’: No such file or directory
Sep 15 14:54:28 localhost cloud-init: /tmp/quickstart-cfn-tools.source: line 325: /root/redhat_ose-register.sh: No such file or directory

**Comment by dougtoppin** [comment] 2017-09-15 15:45
My guess is if the ansible server can't register itself it can't provision the OpenShift environment and that stops the whole process.

**Comment by ngerasimatos** [comment] 2017-09-15 16:11
> My guess is if the ansible server can't register itself it can't provision the OpenShift environment and that stops the whole process.
> 
> From looking at templates/openshift.template I am assuming that the following s3 file is accessible from the region selected (us-east Virginia in my case) ${SCRIPT_PATH}scripts/redhat_ose-register.sh
> 
> I already terminated my stack so I can't check right now.

I am coming to the same conclusion. Have you tried to deploy Origin or only OCP?

**Comment by dougtoppin** [comment] 2017-09-15 16:23
If I am getting the path correctly then this is not accessible to me
https://quickstart-reference.us-east-1.amazonaws.com/redhat/openshift/latest/scripts/redhat_ose-register.sh
I am selecting OpenSource-Version

**Comment by wrlong** [comment] 2017-09-15 16:32
I am following this, only trying OCP:

https://s3.amazonaws.com/quickstart-reference/redhat/openshift/latest/doc/red-hat-openshift-on-the-aws-cloud.pdf

And specifically:

Option 1
Deploy OpenShift Container
Platform into a new VPC

Thanks.

**Comment by avattathil** [comment] 2017-09-15 17:51
@dougtoppin  @wrlong.  The s3 bucket was missing `redhat_ose-register.sh` Just uploaded it. Please try again

**Comment by avattathil** [comment] 2017-09-15 17:56
Fixed in https://github.com/aws-quickstart/quickstart-redhat-openshift/commit/7cde90472e3430d8ebeb1d206f9008b01821a358

**Comment by ngerasimatos** [comment] 2017-09-15 18:00
Testing

**Comment by dougtoppin** [comment] 2017-09-15 18:53
Trying it again. The ansible server is logging this:

ep 15 18:48:48 localhost dbus-daemon: dbus[553]: [system] Successfully activated service 'com.redhat.SubscriptionManager'
Sep 15 18:48:55 localhost cloud-init: Error: 'rhel-7-server-ose-3.6-rpms' does not match a valid repository ID. Use "subscription-manager repos --list" to see valid repositories.
Sep 15 18:48:55 localhost cloud-init: Error: 'rhel-7-server-extras-rpms' does not match a valid repository ID. Use "subscription-manager repos --list" to see valid repositories.
Sep 15 18:48:55 localhost cloud-init: Error: 'rhel-7-fast-datapath-rpms' does not match a valid repository ID. Use "subscription-manager repos --list" to see valid repositories.
Sep 15 18:48:55 localhost cloud-init: Retrying ....
Sep 15 18:48:58 localhost cloud-init: Loaded plugins: amazon-id, rhui-lb, search-disabled-repos
Sep 15 18:48:58 localhost cloud-init: Cleaning repos: epel rhui-REGION-client-config-server-7
Sep 15 18:48:58 localhost cloud-init: : rhui-REGION-rhel-server-releases

**Comment by ngerasimatos** [comment] 2017-09-15 18:57
I am seeing the following in the CF output.

Embedded stack arn:aws:cloudformation:us-east-2:310649551054:stack/OCP-OpenShiftStack-UQ4BXAPG6997/e0fb5950-9a41-11e7-b9bf-50a68a1b16c6 was not successfully created: The following resource(s) failed to create: [AnsibleConfigServer].

Ansible server shows the same as @dougtoppin noted.

**Comment by avattathil** [comment] 2017-09-15 18:58
@dougtoppin  can you post the output of `yum repolist`

**Comment by dougtoppin** [comment] 2017-09-15 19:01
```
# yum repolist
Loaded plugins: amazon-id, rhui-lb, search-disabled-repos
epel/x86_64/metalink                                                                                                                                                         |  13 kB  00:00:00
epel                                                                                                                                                                         | 4.3 kB  00:00:00
rhui-REGION-client-config-server-7                                                                                                                                           | 2.9 kB  00:00:00
rhui-REGION-rhel-server-releases                                                                                                                                             | 3.5 kB  00:00:00
rhui-REGION-rhel-server-rh-common                                                                                                                                            | 3.8 kB  00:00:00
(1/10): epel/x86_64/group_gz                                                                                                                                                 | 170 kB  00:00:00
(2/10): rhui-REGION-client-config-server-7/x86_64/primary_db                                                                                                                 | 5.5 kB  00:00:00
(3/10): rhui-REGION-rhel-server-releases/7Server/x86_64/group                                                                                                                | 709 kB  00:00:00
(4/10): epel/x86_64/updateinfo                                                                                                                                               | 821 kB  00:00:00
(5/10): rhui-REGION-rhel-server-releases/7Server/x86_64/updateinfo                                                                                                           | 2.3 MB  00:00:00
(6/10): rhui-REGION-rhel-server-rh-common/7Server/x86_64/group                                                                                                               |  104 B  00:00:00
(7/10): rhui-REGION-rhel-server-rh-common/7Server/x86_64/updateinfo                                                                                                          |  32 kB  00:00:00
(8/10): rhui-REGION-rhel-server-rh-common/7Server/x86_64/primary_db                                                                                                          | 119 kB  00:00:00
(9/10): rhui-REGION-rhel-server-releases/7Server/x86_64/primary_db                                                                                                           |  43 MB  00:00:00
(10/10): epel/x86_64/primary_db                                                                                                                                              | 4.8 MB  00:00:01
repo id                                                                                repo name                                                                                              status
epel/x86_64                                                                            Extra Packages for Enterprise Linux 7 - x86_64                                                         11,904
rhui-REGION-client-config-server-7/x86_64                                              Red Hat Update Infrastructure 2.0 Client Configuration Server 7                                             6
rhui-REGION-rhel-server-releases/7Server/x86_64                                        Red Hat Enterprise Linux Server 7 (RPMs)                                                               17,215
rhui-REGION-rhel-server-rh-common/7Server/x86_64                                       Red Hat Enterprise Linux Server 7 RH Common (RPMs)                                                        228
repolist: 29,353
#
```

**Comment by avattathil** [comment] 2017-09-15 19:25
@dougtoppin  it looks like you don't have the Openshift entitlements? or at least they are not getting attached!

**Comment by dougtoppin** [comment] 2017-09-15 19:27
It is probably a good idea to list exactly what is needed in the readme. I was not sure even what to look for. Do you know what the entitlements that are needed actually are?

**Comment by avattathil** [comment] 2017-09-15 19:33
Yes, I agree. I am compiling notes as I work with you and will update the Readme. 

This link https://www.redhat.com/wapps/eval/index.html?evaluation_id=1026 is from a @ngerasimatos post from another reply. Can you register your rhn id and try again?

**Comment by dougtoppin** [comment] 2017-09-15 19:35
btw, one issue is that to get these subscriptions a personal email address cannot be used. it has to be a profession one which makes this more difficult.

**Comment by avattathil** [comment] 2017-09-15 19:41
I see - I will raise that with the Red hat team

**Comment by avattathil** [comment] 2017-09-15 19:43
Here is the output on **`yum repolist`** from stack.

repo id                                                     repo name                                                                         status
epel/x86_64                                                 Extra Packages for Enterprise Linux 7 - x86_64                                    11,904
rhel-7-fast-datapath-rpms/7Server/x86_64                    Red Hat Enterprise Linux Fast Datapath (RHEL 7 Server) (RPMs)                         38
rhel-7-rc-rpms                                              Red Hat Enterprise Linux 7 Server Release Candidate (RPMs)                         4,323
rhel-7-server-aus-rpms/7Server/x86_64                       Red Hat Enterprise Linux 7 Server - AUS (RPMs)                                    11,925
rhel-7-server-extras-rpms/x86_64                            Red Hat Enterprise Linux 7 Server - Extras (RPMs)                                    639
rhel-7-server-htb-rpms/x86_64                               Red Hat Enterprise Linux 7 Server HTB (RPMs)                                       7,592
rhel-7-server-nfv-rpms/7Server/x86_64                       Red Hat Enterprise Linux for Real Time for NFV (RHEL 7 Server) (RPMs)                216
rhel-7-server-ose-3.6-rpms/x86_64                           **Red Hat OpenShift Container Platform 3.6** (RPMs)                                      523
rhel-7-server-rpms/7Server/x86_64                           Red Hat Enterprise Linux 7 Server (RPMs)                                          17,215
rhel-7-server-rt-beta-rpms/x86_64                           Red Hat Enterprise Linux for Real Time Beta (RHEL 7 Server) (RPMs)                    15
rhel-7-server-rt-htb-rpms/x86_64                            Red Hat Enterprise Linux for Real Time HTB (RHEL 7 Server) (RPMs)                      0
rhel-7-server-rt-rpms/7Server/x86_64                        Red Hat Enterprise Linux for Real Time (RHEL 7 Server) (RPMs)                        233
rhel-7-server-tus-rpms/7Server/x86_64                       Red Hat Enterprise Linux 7 Server - TUS (RPMs)                                    11,925
rhui-REGION-client-config-server-7/x86_64                   Red Hat Update Infrastructure 2.0 Client Configuration Server 7                        0
rhui-REGION-rhel-server-releases/7Server/x86_64             Red Hat Enterprise Linux Server 7 (RPMs)                                          17,215
rhui-REGION-rhel-server-rh-common/7Server/x86_64            Red Hat Enterprise Linux Server 7 RH Common (RPMs)

**Comment by dougtoppin** [comment] 2017-09-15 20:14
I think that the instructions should include something very specific in terms of what subscriptions are needed and how to determine what are available to the user before they try the Quick Start. Otherwise it might take an hour or more (along with troubleshooting) to determine that they either cannot use it at all or that there are not enough subscriptions available to run it. 

It is also a good idea to note that using the Quick Start will take subscriptions from their work account if any are available so using the QS is not a casual activity.

Also that the RH portal requires a professional email addressed associated account (meaning not gmail I guess) so even if someone wants to register they may have a difficult time with it.

My company just made me a channel administrator for our account and now I can see that there are no entitlement available so I will not be able to run the Quick Start unfortunately.

**Comment by avattathil** [comment] 2017-09-15 20:29
Ok, I see! That is unfortunate indeed.   
Your reports along with @wrlong and @ngerasimatos did help me to fix a valid issue so I appreciate the assistance. I just did a test to make sure I could launch successfully. I will be merging your PR into a development branch for now and also be updating the guide with you suggestions.

**Comment by avattathil** [comment] 2017-09-15 20:34
@wrlong Please reopen if the applied fix https://github.com/aws-quickstart/quickstart-redhat-openshift/commit/7cde90472e3430d8ebeb1d206f9008b01821a358 did not resolve this issue

**Closed by avattathil** 2017-09-15 20:34 UTC
Labels: bug

**Comment by wrlong** [comment] 2017-09-15 22:03
Thanks alot @avattathil - things are still running, but well past this issue and playbooks are running:

Sep 15 22:00:53 localhost cloud-init: [INFO] Starting OpenShift Cluster Build (Beginning Ansible Playbook run!!!)

Thanks!
