### ISSUE TITLE
Successful CloudFormation Deployment but Openshift not installed

### ISSUE THREAD

**Issue by skaminskitx** [aws-quickstart/quickstart-redhat-openshift#38] opened 2018-02-08 01:24 UTC
Tried multiple times in multiple regions using both option 1 and option 2 for the deployment with basically the same result.

Openshift doesn't look to have been installed on any of the nodes.  On the masters, there is no /etc/origin/master and although there's a folder for /etc/origin/node, there's no config file.

Looking on the ansible host that's deployed, there is no information for host names in the /etc/ansible/hosts file so it seems that the OCP install couldn't run.  I manually added the hostnames in as a test and then received an error about the openshift name being longer than 63 characters.

It seems that in the template files, there's a call for /bin/aws-ocp-qa-scale to build the inventory but that file doesn't exist on the ansible server so the ec2 inventory is never added to the ansible host file.

So it seems I have two issues.  Not sure if the longer than 63 character cluster name is the primary issue or a secondary issue to the possibly missing /bin/aws-ocp-qa-scale file.

**Comment by avattathil** [comment] 2018-02-08 03:00
I just deployed successfully using the New VPC option from the quickstart page: https://aws.amazon.com/quickstart/architecture/openshift/

Launched in us-east-2 using the link below:
https://console.aws.amazon.com/cloudformation/home?region=us-east-2#/stacks/new?stackName=Red-Hat-OpenShift&templateURL=https://s3.amazonaws.com/quickstart-reference/redhat/openshift/latest/templates/openshift-master.template

I was able to hit the UI provided by the Stacks Outputs

**Comment by mirwin77** [comment] 2018-02-08 17:29
I'm running in to the same issues as skaminskitx.  Here are the relevant logs from the ansible host.  It appears to be an issue with S3 bucket creation during deployment.

Feb 07 20:47:13 ip-10-3-27-201.us-east-2.compute.internal
cloud-init[1612]: + aws s3 cp s3://quickstart-reference/redhat/openshift/latest/scripts/scaling /root/ose_scaling --recursive
Feb 07 20:47:13 ip-10-3-27-201.us-east-2.compute.internal cloud-init[1612]: fatal error: An error occurred (AccessDenied) when calling the ListObjects operation: Access Denied

Feb 07 16:29:11 ip-10-3-15-90.us-east-2.compute.internal cloud-init[1606]: + /bin/aws-ose-qs-scale --generate-initial-inventory
Feb 07 16:29:11 ip-10-3-15-90.us-east-2.compute.internal cloud-init[1606]: /var/lib/cloud/instance/scripts/part-001: line 70: /bin/aws-ose-qs-scale: No such file or directory
Feb 07 16:29:11 ip-10-3-15-90.us-east-2.compute.internal cloud-init[1606]: + cat '/tmp/openshift_ansible_inventory*'
Feb 07 16:29:11 ip-10-3-15-90.us-east-2.compute.internal cloud-init[1606]: cat: /tmp/openshift_ansible_inventory*: No such file or directory

**Comment by avattathil** [comment] 2018-02-08 17:39
Thank you for the additional logs. Continuing to investigate

**Comment by avattathil** [comment] 2018-02-08 18:25
**Issue confirmed!** The failure is due to the `quickstart-reference` bucket not allowing ListObjects operation.  Working on a fix. 

**For immediate workaround.** 
`git clone --recursive https://github.com/aws-quickstart/quickstart-redhat-openshift.git`
`git checkout master`
Copy the contents to an s3 bucket that allows recursive s3 copy (ListObjects operation)
Update the `QSS3BucketName` and  `QSS3KeyPrefix` accordingly

**Comment by mirwin77** [comment] 2018-02-09 15:49
I'm unable to clone the submodules when attempting to follow the workaround.  I assume this is related to:
https://github.com/aws-quickstart/quickstart-redhat-openshift/pull/41

[mirwin@vireo aws-quickstart]$ git clone --recursive https://github.com/aws-quickstart/quickstart-redhat-openshift.git
Cloning into 'quickstart-redhat-openshift'...
remote: Counting objects: 1560, done.
remote: Total 1560 (delta 0), reused 0 (delta 0), pack-reused 1560
Receiving objects: 100% (1560/1560), 10.12 MiB | 14.83 MiB/s, done.
Resolving deltas: 100% (602/602), done.
Submodule 'submodules/quickstart-aws-vpc' (git@github.com:aws-quickstart/quickstart-aws-vpc.git) registered for path 'submodules/quickstart-aws-vpc'
Submodule 'submodules/quickstart-linux-utilities' (git@github.com:aws-quickstart/quickstart-linux-utilities.git) registered for path 'submodules/quickstart-linux-utilities'
Cloning into 'submodules/quickstart-aws-vpc'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Clone of 'git@github.com:aws-quickstart/quickstart-aws-vpc.git' into submodule path 'submodules/quickstart-aws-vpc' failed

**Comment by avattathil** [comment] 2018-02-09 17:22
Submodules issue is corrected in https://github.com/aws-quickstart/quickstart-redhat-openshift/commit/ee0d53bbd31c5e0b862e890dc49e3bba17ced908 (please verify)
Finalizing fix for recursive copy issue

**Comment by avattathil** [comment] 2018-02-09 19:18
Fix applied to in s3:
https://console.aws.amazon.com/cloudformation/home?region=us-east-2#/stacks/new?stackName=Red-Hat-OpenShift&templateURL=https://s3.amazonaws.com/quickstart-reference/redhat/openshift/latest/templates/openshift-master.template
@skaminskitx @mirwin77  Please validate that this issue is resolved

**Comment by mirwin77** [comment] 2018-02-09 20:59
Looking good now!  Thanks for the quick fix.

[root@ip-10-196-53-178 ~]# oc login -u system:admin
Logged into "https://internal-ITS-RedHa-OpenShif-WGC91TR4BVGM-739217134.us-east-2.elb.amazonaws.com:8443" as "system:admin" using existing credentials.

You have access to the following projects and can switch between them with 'oc project <projectname>':

  * default
    kube-public
    kube-service-catalog
    kube-system
    logging
    management-infra
    openshift
    openshift-ansible-service-broker
    openshift-infra
    openshift-node
    openshift-template-service-broker

Using project "default".
[root@ip-10-196-53-178 ~]# oc get node
NAME            STATUS                     AGE       VERSION
10.196.48.195   Ready                      14m       v1.7.6+a08f5eeb62
10.196.48.204   Ready,SchedulingDisabled   14m       v1.7.6+a08f5eeb62
10.196.50.31    Ready,SchedulingDisabled   14m       v1.7.6+a08f5eeb62
10.196.51.14    Ready                      14m       v1.7.6+a08f5eeb62
10.196.53.121   Ready                      14m       v1.7.6+a08f5eeb62
10.196.53.178   Ready,SchedulingDisabled   14m       v1.7.6+a08f5eeb62

**Comment by avattathil** [comment] 2018-02-09 21:12
Closing per @mirwin77 validation

**Closed by avattathil** 2018-02-09 21:12 UTC
Labels: bug
